[2024-12-03T13:28:33.510+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_file_processing.etl_merge manual__2024-12-03T13:28:30.166136+00:00 [queued]>
[2024-12-03T13:28:33.514+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_file_processing.etl_merge manual__2024-12-03T13:28:30.166136+00:00 [queued]>
[2024-12-03T13:28:33.514+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-12-03T13:28:33.521+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): etl_merge> on 2024-12-03 13:28:30.166136+00:00
[2024-12-03T13:28:33.526+0000] {standard_task_runner.py:57} INFO - Started process 190 to run task
[2024-12-03T13:28:33.529+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_file_processing', 'etl_merge', 'manual__2024-12-03T13:28:30.166136+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/ETL_file_processing.py', '--cfg-path', '/tmp/tmpt5ni0ni3']
[2024-12-03T13:28:33.530+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask etl_merge
[2024-12-03T13:28:33.555+0000] {task_command.py:410} INFO - Running <TaskInstance: etl_file_processing.etl_merge manual__2024-12-03T13:28:30.166136+00:00 [running]> on host 9666e9771178
[2024-12-03T13:28:33.596+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_file_processing' AIRFLOW_CTX_TASK_ID='etl_merge' AIRFLOW_CTX_EXECUTION_DATE='2024-12-03T13:28:30.166136+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-03T13:28:30.166136+00:00'
[2024-12-03T13:28:36.710+0000] {logging_mixin.py:150} INFO - No data to merge.
[2024-12-03T13:28:36.717+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-12-03T13:28:36.768+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=etl_file_processing, task_id=etl_merge, execution_date=20241203T132830, start_date=20241203T132833, end_date=20241203T132836
[2024-12-03T13:28:36.824+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-12-03T13:28:36.861+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
