[2025-01-07T11:14:49.194+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_file_processing.etl_merge manual__2025-01-07T11:14:29.680374+00:00 [queued]>
[2025-01-07T11:14:49.202+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_file_processing.etl_merge manual__2025-01-07T11:14:29.680374+00:00 [queued]>
[2025-01-07T11:14:49.202+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-01-07T11:14:49.213+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): etl_merge> on 2025-01-07 11:14:29.680374+00:00
[2025-01-07T11:14:49.232+0000] {standard_task_runner.py:57} INFO - Started process 2728 to run task
[2025-01-07T11:14:49.238+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_file_processing', 'etl_merge', 'manual__2025-01-07T11:14:29.680374+00:00', '--job-id', '513', '--raw', '--subdir', 'DAGS_FOLDER/ETL_file_processing.py', '--cfg-path', '/tmp/tmprzl0zvu6']
[2025-01-07T11:14:49.239+0000] {standard_task_runner.py:85} INFO - Job 513: Subtask etl_merge
[2025-01-07T11:14:49.305+0000] {task_command.py:410} INFO - Running <TaskInstance: etl_file_processing.etl_merge manual__2025-01-07T11:14:29.680374+00:00 [running]> on host 8fff7f1050bf
[2025-01-07T11:14:49.404+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_file_processing' AIRFLOW_CTX_TASK_ID='etl_merge' AIRFLOW_CTX_EXECUTION_DATE='2025-01-07T11:14:29.680374+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-07T11:14:29.680374+00:00'
[2025-01-07T11:15:05.890+0000] {logging_mixin.py:150} INFO - FR and IH data merged and stored successfully.
[2025-01-07T11:15:05.934+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-01-07T11:15:05.959+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=etl_file_processing, task_id=etl_merge, execution_date=20250107T111429, start_date=20250107T111449, end_date=20250107T111505
[2025-01-07T11:15:06.034+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-01-07T11:15:06.065+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
