[2025-01-07T10:59:10.563+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_file_processing.etl_merge manual__2025-01-07T10:58:51.393123+00:00 [queued]>
[2025-01-07T10:59:10.575+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_file_processing.etl_merge manual__2025-01-07T10:58:51.393123+00:00 [queued]>
[2025-01-07T10:59:10.575+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-01-07T10:59:10.603+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): etl_merge> on 2025-01-07 10:58:51.393123+00:00
[2025-01-07T10:59:10.616+0000] {standard_task_runner.py:57} INFO - Started process 2418 to run task
[2025-01-07T10:59:10.624+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_file_processing', 'etl_merge', 'manual__2025-01-07T10:58:51.393123+00:00', '--job-id', '482', '--raw', '--subdir', 'DAGS_FOLDER/ETL_file_processing.py', '--cfg-path', '/tmp/tmphgmey9np']
[2025-01-07T10:59:10.627+0000] {standard_task_runner.py:85} INFO - Job 482: Subtask etl_merge
[2025-01-07T10:59:10.729+0000] {task_command.py:410} INFO - Running <TaskInstance: etl_file_processing.etl_merge manual__2025-01-07T10:58:51.393123+00:00 [running]> on host 8fff7f1050bf
[2025-01-07T10:59:10.969+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_file_processing' AIRFLOW_CTX_TASK_ID='etl_merge' AIRFLOW_CTX_EXECUTION_DATE='2025-01-07T10:58:51.393123+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-07T10:58:51.393123+00:00'
[2025-01-07T10:59:28.588+0000] {logging_mixin.py:150} INFO - FR and IH data merged and stored successfully.
[2025-01-07T10:59:28.638+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-01-07T10:59:28.667+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=etl_file_processing, task_id=etl_merge, execution_date=20250107T105851, start_date=20250107T105910, end_date=20250107T105928
[2025-01-07T10:59:28.742+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-01-07T10:59:28.777+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
