[2025-01-07T12:09:57.233+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_file_processing.etl_merge manual__2025-01-07T12:08:50.525815+00:00 [queued]>
[2025-01-07T12:09:57.273+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_file_processing.etl_merge manual__2025-01-07T12:08:50.525815+00:00 [queued]>
[2025-01-07T12:09:57.274+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-01-07T12:09:57.325+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): etl_merge> on 2025-01-07 12:08:50.525815+00:00
[2025-01-07T12:09:57.394+0000] {standard_task_runner.py:57} INFO - Started process 4394 to run task
[2025-01-07T12:09:57.414+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_file_processing', 'etl_merge', 'manual__2025-01-07T12:08:50.525815+00:00', '--job-id', '679', '--raw', '--subdir', 'DAGS_FOLDER/ETL_file_processing.py', '--cfg-path', '/tmp/tmpxqyossrp']
[2025-01-07T12:09:57.434+0000] {standard_task_runner.py:85} INFO - Job 679: Subtask etl_merge
[2025-01-07T12:09:57.623+0000] {task_command.py:410} INFO - Running <TaskInstance: etl_file_processing.etl_merge manual__2025-01-07T12:08:50.525815+00:00 [running]> on host 8fff7f1050bf
[2025-01-07T12:09:57.930+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_file_processing' AIRFLOW_CTX_TASK_ID='etl_merge' AIRFLOW_CTX_EXECUTION_DATE='2025-01-07T12:08:50.525815+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-07T12:08:50.525815+00:00'
[2025-01-07T12:10:20.705+0000] {logging_mixin.py:150} INFO - FR and IH data merged and stored successfully.
[2025-01-07T12:10:20.810+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-01-07T12:10:20.867+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=etl_file_processing, task_id=etl_merge, execution_date=20250107T120850, start_date=20250107T120957, end_date=20250107T121020
[2025-01-07T12:10:20.974+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-01-07T12:10:21.055+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
